#############################################################################
# Generated by PAGE version 4.17
# in conjunction with Tcl version 8.6
# Nov 04, 2018 04:07:37 PM WIB  platform: Linux
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

vTcl:font:add_GUI_font TkDefaultFont \
"-family fixed -size 10 -weight normal -slant roman -underline 0 -overstrike 0"
vTcl:font:add_GUI_font TkFixedFont \
"-family fixed -size 10 -weight normal -slant roman -underline 0 -overstrike 0"
vTcl:font:add_GUI_font TkMenuFont \
"-family Helvetica -size -12 -weight normal -slant roman -underline 0 -overstrike 0"
vTcl:font:add_GUI_font TkTextFont \
"-family Helvetica -size -12 -weight normal -slant roman -underline 0 -overstrike 0"
set vTcl(actual_gui_bg) #f5deb3
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #f5deb3
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #b2c9f4
set vTcl(analog_color_p) #eaf4b2
set vTcl(analog_color_m) #f4bcb2
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #f4bcb2
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.bor41 {base} {
    if {$base == ""} {
        set base .bor41
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m47" -background {#d9d9d9} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1024x600+0+40
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1425 870
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "Treadmill"
    vTcl:DefineAlias "$top" "treadmillPage" vTcl:Toplevel:WidgetProc "" 1
    button $top.but43 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -command speed_down -foreground {#000000} \
        -highlightcolor black -text {Speed Down} 
    vTcl:DefineAlias "$top.but43" "speed_down" vTcl:WidgetProc "treadmillPage" 1
    button $top.but44 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -command run -foreground {#000000} \
        -highlightcolor black -text Start 
    vTcl:DefineAlias "$top.but44" "start" vTcl:WidgetProc "treadmillPage" 1
    button $top.but45 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -command speed_up -foreground {#000000} \
        -highlightcolor black -text {Speed Up} 
    vTcl:DefineAlias "$top.but45" "speed_up" vTcl:WidgetProc "treadmillPage" 1
    ttk::separator $top.tSe46
    vTcl:DefineAlias "$top.tSe46" "TSeparator1" vTcl:WidgetProc "treadmillPage" 1
    set site_3_0 $top.m47
    menu $site_3_0 \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    labelframe $top.lab52 \
        -foreground black -text Covered -background {#d9d9d9} -height 155 \
        -highlightcolor black -width 300 
    vTcl:DefineAlias "$top.lab52" "Labelframe2" vTcl:WidgetProc "treadmillPage" 1
    set site_3_0 $top.lab52
    label $site_3_0.lab53 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text 12 
    vTcl:DefineAlias "$site_3_0.lab53" "cov_val" vTcl:WidgetProc "treadmillPage" 1
    label $site_3_0.lab54 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Km 
    vTcl:DefineAlias "$site_3_0.lab54" "Label2_2" vTcl:WidgetProc "treadmillPage" 1
    place $site_3_0.lab53 \
        -in $site_3_0 -x 20 -y 40 -width 144 -relwidth 0 -height 87 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 170 -y 50 -width 94 -height 57 -anchor nw \
        -bordermode ignore 
    labelframe $top.lab55 \
        -foreground black -text HeartRate -background {#d9d9d9} -height 155 \
        -highlightcolor black -width 300 
    vTcl:DefineAlias "$top.lab55" "hrFrame" vTcl:WidgetProc "treadmillPage" 1
    set site_3_0 $top.lab55
    label $site_3_0.lab53 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -text 110 
    vTcl:DefineAlias "$site_3_0.lab53" "hr_val" vTcl:WidgetProc "treadmillPage" 1
    label $site_3_0.lab54 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text bpm 
    vTcl:DefineAlias "$site_3_0.lab54" "Label2_3" vTcl:WidgetProc "treadmillPage" 1
    place $site_3_0.lab53 \
        -in $site_3_0 -x 20 -y 40 -width 134 -relwidth 0 -height 87 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 170 -y 50 -width 94 -height 57 -anchor nw \
        -bordermode ignore 
    labelframe $top.lab56 \
        -foreground black -text {Burned Calories} -background {#d9d9d9} \
        -height 155 -highlightcolor black -width 300 
    vTcl:DefineAlias "$top.lab56" "Labelframe2_4" vTcl:WidgetProc "treadmillPage" 1
    set site_3_0 $top.lab56
    label $site_3_0.lab53 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text 273 
    vTcl:DefineAlias "$site_3_0.lab53" "cal_val" vTcl:WidgetProc "treadmillPage" 1
    label $site_3_0.lab54 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Cal 
    vTcl:DefineAlias "$site_3_0.lab54" "Label2_1" vTcl:WidgetProc "treadmillPage" 1
    place $site_3_0.lab53 \
        -in $site_3_0 -x 20 -y 30 -width 144 -relwidth 0 -height 97 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 170 -y 50 -width 94 -height 57 -anchor nw \
        -bordermode ignore 
    labelframe $top.lab57 \
        -foreground black -text Steps -background {#d9d9d9} -height 155 \
        -highlightcolor black -width 300 
    vTcl:DefineAlias "$top.lab57" "Labelframe2_2" vTcl:WidgetProc "treadmillPage" 1
    set site_3_0 $top.lab57
    label $site_3_0.lab53 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text 115 
    vTcl:DefineAlias "$site_3_0.lab53" "step_value" vTcl:WidgetProc "treadmillPage" 1
    label $site_3_0.lab54 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Steps/min 
    vTcl:DefineAlias "$site_3_0.lab54" "Label2_4" vTcl:WidgetProc "treadmillPage" 1
    place $site_3_0.lab53 \
        -in $site_3_0 -x 20 -y 30 -width 144 -relwidth 0 -height 97 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 170 -y 50 -width 94 -height 57 -anchor nw \
        -bordermode ignore 
    labelframe $top.lab60 \
        -foreground black -text Speed -background {#d9d9d9} -height 315 \
        -highlightcolor black -width 360 
    vTcl:DefineAlias "$top.lab60" "Labelframe3" vTcl:WidgetProc "treadmillPage" 1
    set site_3_0 $top.lab60
    label $site_3_0.lab61 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text 10 
    vTcl:DefineAlias "$site_3_0.lab61" "speed_val" vTcl:WidgetProc "treadmillPage" 1
    label $site_3_0.lab63 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Km/hr 
    vTcl:DefineAlias "$site_3_0.lab63" "Label3_4" vTcl:WidgetProc "treadmillPage" 1
    place $site_3_0.lab61 \
        -in $site_3_0 -x 10 -y 30 -width 324 -relwidth 0 -height 147 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab63 \
        -in $site_3_0 -x 10 -y 170 -width 324 -relwidth 0 -height 137 \
        -relheight 0 -anchor nw -bordermode ignore 
    button $top.but40 \
        -activebackground {#f4bcb2} -activeforeground black \
        -background {#d9d9d9} -command destroy_window -foreground {#000000} \
        -highlightcolor black -text Back 
    vTcl:DefineAlias "$top.but40" "back" vTcl:WidgetProc "treadmillPage" 1
    button $top.but41 \
        -activebackground {#f4bcb2} -activeforeground black \
        -background {#d9d9d9} -command recap -foreground {#000000} \
        -highlightcolor black -text Recap 
    vTcl:DefineAlias "$top.but41" "recap" vTcl:WidgetProc "treadmillPage" 1
    labelframe $top.lab41 \
        -foreground black -text Timer -background {#d9d9d9} -height 105 \
        -highlightcolor black -width 980 
    vTcl:DefineAlias "$top.lab41" "Labelframe1" vTcl:WidgetProc "treadmillPage" 1
    set site_3_0 $top.lab41
    label $site_3_0.lab42 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Label 
    vTcl:DefineAlias "$site_3_0.lab42" "timer" vTcl:WidgetProc "treadmillPage" 1
    place $site_3_0.lab42 \
        -in $site_3_0 -x 480 -y 50 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but43 \
        -in $top -x 20 -y 540 -width 280 -relwidth 0 -height 45 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but44 \
        -in $top -x 310 -y 540 -width 410 -relwidth 0 -height 45 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but45 \
        -in $top -x 730 -y 540 -width 280 -relwidth 0 -height 45 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tSe46 \
        -in $top -x 0 -y 0 -rely 0.867 -width 1024 -relwidth 0 -anchor nw \
        -bordermode inside 
    place $top.lab52 \
        -in $top -x 30 -y 350 -width 300 -relwidth 0 -height 155 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab55 \
        -in $top -x 30 -y 190 -width 300 -height 155 -anchor nw \
        -bordermode ignore 
    place $top.lab56 \
        -in $top -x 710 -y 190 -width 300 -height 155 -anchor nw \
        -bordermode ignore 
    place $top.lab57 \
        -in $top -x 710 -y 350 -width 300 -height 155 -anchor nw \
        -bordermode ignore 
    place $top.lab60 \
        -in $top -x 340 -y 190 -width 360 -relwidth 0 -height 315 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.but40 \
        -in $top -x 30 -y 20 -width 62 -relwidth 0 -height 45 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but41 \
        -in $top -x 950 -y 20 -width 62 -height 45 -anchor nw \
        -bordermode ignore 
    place $top.lab41 \
        -in $top -x 30 -y 80 -width 980 -relwidth 0 -height 105 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .bor41 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

