#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.17
# In conjunction with Tcl version 8.6
#    Oct 21, 2018 03:22:40 PM WIB  platform: Linux

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import connect_msg_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Connect_Mi_Band_2 (root)
    connect_msg_support.init(root, top)
    root.mainloop()

w = None
def create_Connect_Mi_Band_2(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Connect_Mi_Band_2 (w)
    connect_msg_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Connect_Mi_Band_2():
    global w
    w.destroy()
    w = None


class Connect_Mi_Band_2:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 

        top.geometry("500x365+266+121")
##        top.attributes("-fullscreen", True)
        top.title("Connect Mi Band 2")



        self.but40 = Button(top)
        self.but40.place(relx=0.21, rely=0.745, height=45, width=280)
        self.but40.configure(activebackground="#d9d9d9")
        self.but40.configure(command=connect_msg_support.connect)
        self.but40.configure(text='''Connect!''')
        self.but40.configure(width=112)

        self.Label1 = Label(top)
        self.Label1.place(relx=0.22, rely=0.14, height=100, width=270)
        self.Label1.configure(text='''Connecting Mi Band...''',font=("Helvetica", 20))
        self.Label1.configure(width=254)






if __name__ == '__main__':
    vp_start_gui()



