#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.17
# In conjunction with Tcl version 8.6
#    Oct 21, 2018 03:22:33 PM WIB  platform: Linux

import sys
sys.path.insert(0, 'MiBand2/')

import time
from base import MiBand2
from constants import ALERT_TYPES

#MAC ADDRESS MI BAND 2
MAC = 'D6:EC:F2:B3:70:BA'

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def connect():
    print('connect_msg_support.connect')
    sys.stdout.flush()
    print('initiate mi band 2')
    sys.stdout.flush()
    band = MiBand2(MAC, debug=True)
    band.setSecurityLevel(level="medium")
    if band.initialize():
        w.Label1.configure(text='''Mi Band Connected!''')
        w.but40.configure(text="Ok", command=destroy_window)
    band.disconnect()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import connect_msg
    connect_msg.vp_start_gui()


