#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.17
# In conjunction with Tcl version 8.6
#    Nov 14, 2018 11:40:26 AM WIB  platform: Linux

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import halaman_manual_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Treadmill (root)
    halaman_manual_support.init(root, top)
    root.mainloop()

w = None
def create_Treadmill(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Treadmill (w)
    halaman_manual_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Treadmill():
    global w
    w.destroy()
    w = None


class Treadmill:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 

        top.geometry("1024x600+-5+51")
        top.title("Treadmill")



        self.Button1 = Button(top)
        self.Button1.place(relx=0.029, rely=0.617, height=45, width=172)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(text='''Button''')
        self.Button1.configure(width=172)

        self.Button1_5 = Button(top)
        self.Button1_5.place(relx=0.215, rely=0.617, height=45, width=172)
        self.Button1_5.configure(activebackground="#d9d9d9")
        self.Button1_5.configure(text='''Button''')

        self.Button1_6 = Button(top)
        self.Button1_6.place(relx=0.41, rely=0.617, height=45, width=192)
        self.Button1_6.configure(activebackground="#d9d9d9")
        self.Button1_6.configure(text='''Button''')
        self.Button1_6.configure(width=192)

        self.Button1_7 = Button(top)
        self.Button1_7.place(relx=0.625, rely=0.617, height=45, width=172)
        self.Button1_7.configure(activebackground="#d9d9d9")
        self.Button1_7.configure(text='''Button''')

        self.Button1_8 = Button(top)
        self.Button1_8.place(relx=0.811, rely=0.617, height=45, width=172)
        self.Button1_8.configure(activebackground="#d9d9d9")
        self.Button1_8.configure(text='''Button''')






if __name__ == '__main__':
    vp_start_gui()



