#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.17
# In conjunction with Tcl version 8.6
#    Oct 15, 2018 03:30:21 PM WIB  platform: Linux

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import homepage_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Treadmill (root)
    homepage_support.init(root, top)
    root.mainloop()

w = None
def create_Treadmill(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Treadmill (w)
    homepage_support.init(w, top, *args, **kwargs)
    root.attributes("-fullscreen", True)
    return (w, top)

def destroy_Treadmill():
    global w
    w.destroy()
    w = None


class Treadmill:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#f5deb3'  # X11 color: 'wheat'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font18 = "TkDefaultFont"
        font9 = "TkDefaultFont"
        font30 = "-family fixed -size 30 -weight bold -slant roman "  \
            "-underline 0 -overstrike 0"

        top.geometry("1024x600+0+0")
        top.attributes("-fullscreen", True)
        top.title("Treadmill")
        top.configure(highlightcolor="black")



        self.Labelframe1 = LabelFrame(top)
        self.Labelframe1.place(relx=0.029, rely=0.15, relheight=0.542
                , relwidth=0.946)
        self.Labelframe1.configure(relief=GROOVE)
        self.Labelframe1.configure(text='''Treadmill Mode''')
        self.Labelframe1.configure(width=980)

        self.mode1 = Button(self.Labelframe1)
        self.mode1.place(relx=0.02, rely=0.092, height=265, width=132
                , bordermode='ignore')
        self.mode1.configure(activebackground="#d9d9d9")
        self.mode1.configure(command=homepage_support.recovery)
        self.mode1.configure(font="TkFixedFont")
        self.mode1.configure(text='''Recovery''')

        self.mode2 = Button(self.Labelframe1)
        self.mode2.place(relx=0.184, rely=0.092, height=265, width=132
                , bordermode='ignore')
        self.mode2.configure(activebackground="#d9d9d9")
        self.mode2.configure(command=homepage_support.aerobic)
        self.mode2.configure(font="TkFixedFont")
        self.mode2.configure(text='''Aerobic''')

        self.mode3 = Button(self.Labelframe1)
        self.mode3.place(relx=0.347, rely=0.092, height=265, width=132
                , bordermode='ignore')
        self.mode3.configure(activebackground="#d9d9d9")
        self.mode3.configure(command=homepage_support.exteendu)
        self.mode3.configure(font="TkFixedFont")
        self.mode3.configure(text='''Extensive\nEndurance''')

        self.mode4 = Button(self.Labelframe1)
        self.mode4.place(relx=0.51, rely=0.092, height=265, width=132
                , bordermode='ignore')
        self.mode4.configure(activebackground="#d9d9d9")
        self.mode4.configure(command=homepage_support.inteendu)
        self.mode4.configure(text='''Intensive\nEndurance''')
        self.mode4.configure(width=122)

        self.mode5 = Button(self.Labelframe1)
        self.mode5.place(relx=0.673, rely=0.092, height=265, width=132
                , bordermode='ignore')
        self.mode5.configure(activebackground="#d9d9d9")
        self.mode5.configure(command=homepage_support.anaetres)
        self.mode5.configure(font=font18)
        self.mode5.configure(state=ACTIVE)
        self.mode5.configure(text='''Anaerobic\nTreshold''')

        self.mode6 = Button(self.Labelframe1)
        self.mode6.place(relx=0.837, rely=0.092, height=265, width=132
                , bordermode='ignore')
        self.mode6.configure(activebackground="#d9d9d9")
        self.mode6.configure(command=homepage_support.maxaer)
        self.mode6.configure(text='''Maximum\nAerobic''')

        self.Label1 = Label(top)
        self.Label1.place(relx=0.039, rely=0.067, height=50, width=250)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(font=font30)
        self.Label1.configure(text='''iTreadmill''')

        self.Labelframe2 = LabelFrame(top)
        self.Labelframe2.place(relx=0.029, rely=0.717, relheight=0.225
                , relwidth=0.946)
        self.Labelframe2.configure(relief=GROOVE)
        self.Labelframe2.configure(text='''Settings''')
        self.Labelframe2.configure(width=980)

        self.register = Button(self.Labelframe2)
        self.register.place(relx=0.02, rely=0.222, height=85, width=292
                , bordermode='ignore')
        self.register.configure(activebackground="#d9d9d9")
        self.register.configure(command=homepage_support.register)
        self.register.configure(font="TkFixedFont")
        self.register.configure(text='''Register''')

        self.connect = Button(self.Labelframe2)
        self.connect.place(relx=0.347, rely=0.222, height=85, width=292
                , bordermode='ignore')
        self.connect.configure(activebackground="#d9d9d9")
        self.connect.configure(command=homepage_support.connect)
        self.connect.configure(font="TkFixedFont")
        self.connect.configure(state=ACTIVE)
        self.connect.configure(text='''Connect Mi Band''')

        self.other = Button(self.Labelframe2)
        self.other.place(relx=0.673, rely=0.222, height=85, width=292
                , bordermode='ignore')
        self.other.configure(activebackground="#d9d9d9")
        self.other.configure(command=homepage_support.other)
        self.other.configure(font="TkFixedFont")
        self.other.configure(text='''Manual Treadmill''')

        self.menubar = Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)
        
        self.exit = Button(top)
        self.exit.place(relx=0.928, rely=0.033, height=45, width=62)
        self.exit.configure(activebackground="#f4bcb2")
        self.exit.configure(command=homepage_support.destroy_window)
        self.exit.configure(text="Exit")

    def connect():
        if band.initialize():
            print("Init OK")
        band.set_heart_monitor_sleep_support(enabled=False)
        band.disconnect()





if __name__ == '__main__':
    vp_start_gui()



