#############################################################################
# Generated by PAGE version 4.17
# in conjunction with Tcl version 8.6
# Oct 15, 2018 04:16:19 PM WIB  platform: Linux
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

vTcl:font:add_GUI_font TkDefaultFont \
"-family fixed -size 10 -weight normal -slant roman -underline 0 -overstrike 0"
vTcl:font:add_GUI_font TkFixedFont \
"-family fixed -size 10 -weight normal -slant roman -underline 0 -overstrike 0"
vTcl:font:add_GUI_font TkMenuFont \
"-family Helvetica -size -12 -weight normal -slant roman -underline 0 -overstrike 0"
vTcl:font:add_GUI_font TkTextFont \
"-family Helvetica -size -12 -weight normal -slant roman -underline 0 -overstrike 0"
set vTcl(actual_gui_bg) #f5deb3
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #f5deb3
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #b2c9f4
set vTcl(analog_color_p) #eaf4b2
set vTcl(analog_color_m) #f4bcb2
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #f4bcb2
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.bor22 {base} {
    if {$base == ""} {
        set base .bor22
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1036x600+150+109
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1425 870
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "Treadmill"
    vTcl:DefineAlias "$top" "Treadmill" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure TNotebook -background #f5deb3
    ttk::style configure TNotebook.Tab -background #f5deb3
    ttk::style configure TNotebook.Tab -foreground #000000
    ttk::style configure TNotebook.Tab -font TkDefaultFont
    ttk::style map TNotebook.Tab -background [list disabled #f5deb3 selected #d9d9d9]
    ttk::notebook $top.tNo40 \
        -width 1002 -height 532 -takefocus {} 
    vTcl:DefineAlias "$top.tNo40" "TNotebook1" vTcl:WidgetProc "Treadmill" 1
    frame $top.tNo40.t1 \
        -background {#d9d9d9} -highlightcolor black 
    vTcl:DefineAlias "$top.tNo40.t1" "TNotebook1_t0" vTcl:WidgetProc "Treadmill" 1
    $top.tNo40 add $top.tNo40.t1 \
        -padding 0 -sticky nsew -state normal -text Graph -image {} \
        -compound left -underline -1 
    set site_4_0  $top.tNo40.t1
    canvas $site_4_0.can41 \
        -background {#d9d9d9} -borderwidth 2 -closeenough 1.0 -height 441 \
        -highlightcolor black -insertbackground black -relief ridge \
        -selectbackground {#c4c4c4} -selectforeground black -width 821 
    vTcl:DefineAlias "$site_4_0.can41" "Canvas1" vTcl:WidgetProc "Treadmill" 1
    label $site_4_0.lab43 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Heart Rate} 
    vTcl:DefineAlias "$site_4_0.lab43" "Label1" vTcl:WidgetProc "Treadmill" 1
    label $site_4_0.lab44 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Max :} 
    vTcl:DefineAlias "$site_4_0.lab44" "Label2" vTcl:WidgetProc "Treadmill" 1
    label $site_4_0.lab45 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text max_value 
    vTcl:DefineAlias "$site_4_0.lab45" "Label3" vTcl:WidgetProc "Treadmill" 1
    label $site_4_0.lab46 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Average :} 
    vTcl:DefineAlias "$site_4_0.lab46" "Label4" vTcl:WidgetProc "Treadmill" 1
    label $site_4_0.lab47 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text average_value 
    vTcl:DefineAlias "$site_4_0.lab47" "Label3" vTcl:WidgetProc "Treadmill" 1
    place $site_4_0.can41 \
        -in $site_4_0 -x 80 -y 60 -width 821 -relwidth 0 -height 441 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab43 \
        -in $site_4_0 -x 80 -y 30 -width 84 -relwidth 0 -height 17 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab44 \
        -in $site_4_0 -x 210 -y 30 -anchor nw -bordermode ignore 
    place $site_4_0.lab45 \
        -in $site_4_0 -x 270 -y 30 -width 78 -relwidth 0 -height 17 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab46 \
        -in $site_4_0 -x 400 -y 30 -anchor nw -bordermode ignore 
    place $site_4_0.lab47 \
        -in $site_4_0 -x 480 -y 30 -width 108 -relwidth 0 -height 17 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.tNo40.t0 \
        -background {#d9d9d9} -highlightcolor black 
    vTcl:DefineAlias "$top.tNo40.t0" "TNotebook1_t1" vTcl:WidgetProc "Treadmill" 1
    $top.tNo40 add $top.tNo40.t0 \
        -padding 0 -sticky nsew -state normal -text Recap -image {} \
        -compound left -underline -1 
    set site_4_1  $top.tNo40.t0
    labelframe $site_4_1.lab48 \
        -foreground black -text Labelframe -background {#d9d9d9} -height 485 \
        -highlightcolor black -width 960 
    vTcl:DefineAlias "$site_4_1.lab48" "Labelframe1" vTcl:WidgetProc "Treadmill" 1
    set site_5_0 $site_4_1.lab48
    labelframe $site_5_0.lab49 \
        -foreground black -text {Average Heart Rate} -background {#d9d9d9} \
        -height 145 -highlightcolor black -width 150 
    vTcl:DefineAlias "$site_5_0.lab49" "Labelframe2" vTcl:WidgetProc "Treadmill" 1
    set site_6_0 $site_5_0.lab49
    label $site_6_0.lab59 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Label 
    vTcl:DefineAlias "$site_6_0.lab59" "Label5" vTcl:WidgetProc "Treadmill" 1
    label $site_6_0.lab60 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text BPM 
    vTcl:DefineAlias "$site_6_0.lab60" "Label5" vTcl:WidgetProc "Treadmill" 1
    place $site_6_0.lab59 \
        -in $site_6_0 -x 20 -y 30 -width 114 -height 37 -anchor nw \
        -bordermode ignore 
    place $site_6_0.lab60 \
        -in $site_6_0 -x 20 -y 80 -width 114 -height 37 -anchor nw \
        -bordermode ignore 
    labelframe $site_5_0.lab50 \
        -foreground black -text {Total Steps} -background {#d9d9d9} \
        -height 145 -highlightcolor black -width 150 
    vTcl:DefineAlias "$site_5_0.lab50" "Labelframe2" vTcl:WidgetProc "Treadmill" 1
    set site_6_0 $site_5_0.lab50
    label $site_6_0.lab63 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Label 
    vTcl:DefineAlias "$site_6_0.lab63" "Label5" vTcl:WidgetProc "Treadmill" 1
    label $site_6_0.lab65 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Steps 
    vTcl:DefineAlias "$site_6_0.lab65" "Label5" vTcl:WidgetProc "Treadmill" 1
    place $site_6_0.lab63 \
        -in $site_6_0 -x 20 -y 30 -width 114 -height 37 -anchor nw \
        -bordermode ignore 
    place $site_6_0.lab65 \
        -in $site_6_0 -x 20 -y 80 -width 114 -height 37 -anchor nw \
        -bordermode ignore 
    labelframe $site_5_0.lab51 \
        -foreground black -text {Burned Calories} -background {#d9d9d9} \
        -height 145 -highlightcolor black -width 150 
    vTcl:DefineAlias "$site_5_0.lab51" "Labelframe2" vTcl:WidgetProc "Treadmill" 1
    set site_6_0 $site_5_0.lab51
    label $site_6_0.lab67 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Label 
    vTcl:DefineAlias "$site_6_0.lab67" "Label5" vTcl:WidgetProc "Treadmill" 1
    label $site_6_0.lab68 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Cal 
    vTcl:DefineAlias "$site_6_0.lab68" "Label5" vTcl:WidgetProc "Treadmill" 1
    place $site_6_0.lab67 \
        -in $site_6_0 -x 20 -y 30 -width 114 -height 37 -anchor nw \
        -bordermode ignore 
    place $site_6_0.lab68 \
        -in $site_6_0 -x 20 -y 80 -width 114 -height 37 -anchor nw \
        -bordermode ignore 
    labelframe $site_5_0.lab52 \
        -foreground black -text {Maximum Heart Rate} -background {#d9d9d9} \
        -height 145 -highlightcolor black -width 150 
    vTcl:DefineAlias "$site_5_0.lab52" "Labelframe2" vTcl:WidgetProc "Treadmill" 1
    set site_6_0 $site_5_0.lab52
    label $site_6_0.lab61 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Label 
    vTcl:DefineAlias "$site_6_0.lab61" "Label5" vTcl:WidgetProc "Treadmill" 1
    label $site_6_0.lab62 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text BPM 
    vTcl:DefineAlias "$site_6_0.lab62" "Label5" vTcl:WidgetProc "Treadmill" 1
    place $site_6_0.lab61 \
        -in $site_6_0 -x 20 -y 30 -width 114 -height 37 -anchor nw \
        -bordermode ignore 
    place $site_6_0.lab62 \
        -in $site_6_0 -x 20 -y 80 -width 114 -height 37 -anchor nw \
        -bordermode ignore 
    labelframe $site_5_0.lab53 \
        -foreground black -text {Step Frequency} -background {#d9d9d9} \
        -height 145 -highlightcolor black -width 150 
    vTcl:DefineAlias "$site_5_0.lab53" "Labelframe2" vTcl:WidgetProc "Treadmill" 1
    set site_6_0 $site_5_0.lab53
    label $site_6_0.lab64 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Label 
    vTcl:DefineAlias "$site_6_0.lab64" "Label5" vTcl:WidgetProc "Treadmill" 1
    label $site_6_0.lab66 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Steps 
    vTcl:DefineAlias "$site_6_0.lab66" "Label5" vTcl:WidgetProc "Treadmill" 1
    place $site_6_0.lab64 \
        -in $site_6_0 -x 20 -y 30 -width 114 -height 37 -anchor nw \
        -bordermode ignore 
    place $site_6_0.lab66 \
        -in $site_6_0 -x 20 -y 80 -width 114 -height 37 -anchor nw \
        -bordermode ignore 
    labelframe $site_5_0.lab54 \
        -foreground black -text Covered -background {#d9d9d9} -height 145 \
        -highlightcolor black -width 150 
    vTcl:DefineAlias "$site_5_0.lab54" "Labelframe2" vTcl:WidgetProc "Treadmill" 1
    set site_6_0 $site_5_0.lab54
    label $site_6_0.lab69 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Label 
    vTcl:DefineAlias "$site_6_0.lab69" "Label5" vTcl:WidgetProc "Treadmill" 1
    label $site_6_0.lab70 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Km 
    vTcl:DefineAlias "$site_6_0.lab70" "Label5" vTcl:WidgetProc "Treadmill" 1
    place $site_6_0.lab69 \
        -in $site_6_0 -x 20 -y 30 -width 114 -height 37 -anchor nw \
        -bordermode ignore 
    place $site_6_0.lab70 \
        -in $site_6_0 -x 20 -y 80 -width 114 -height 37 -anchor nw \
        -bordermode ignore 
    labelframe $site_5_0.lab55 \
        -foreground black -text Speed -background {#d9d9d9} -height 145 \
        -highlightcolor black -width 150 
    vTcl:DefineAlias "$site_5_0.lab55" "Labelframe2" vTcl:WidgetProc "Treadmill" 1
    set site_6_0 $site_5_0.lab55
    label $site_6_0.lab57 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Label 
    vTcl:DefineAlias "$site_6_0.lab57" "Label5" vTcl:WidgetProc "Treadmill" 1
    label $site_6_0.lab58 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Km/hr 
    vTcl:DefineAlias "$site_6_0.lab58" "Label5" vTcl:WidgetProc "Treadmill" 1
    place $site_6_0.lab57 \
        -in $site_6_0 -x 20 -y 30 -width 114 -relwidth 0 -height 37 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_0.lab58 \
        -in $site_6_0 -x 20 -y 80 -width 114 -height 37 -anchor nw \
        -bordermode ignore 
    labelframe $site_5_0.lab56 \
        -foreground black -text Time -background {#d9d9d9} -height 145 \
        -highlightcolor black -width 150 
    vTcl:DefineAlias "$site_5_0.lab56" "Labelframe2" vTcl:WidgetProc "Treadmill" 1
    set site_6_0 $site_5_0.lab56
    label $site_6_0.lab71 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Label 
    vTcl:DefineAlias "$site_6_0.lab71" "Label5" vTcl:WidgetProc "Treadmill" 1
    place $site_6_0.lab71 \
        -in $site_6_0 -x 10 -y 50 -width 114 -height 37 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab49 \
        -in $site_5_0 -x 220 -y 120 -width 150 -relwidth 0 -height 145 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab50 \
        -in $site_5_0 -x 400 -y 120 -width 150 -height 145 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab51 \
        -in $site_5_0 -x 580 -y 120 -width 150 -height 145 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab52 \
        -in $site_5_0 -x 220 -y 270 -width 150 -height 145 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab53 \
        -in $site_5_0 -x 400 -y 270 -width 150 -height 145 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab54 \
        -in $site_5_0 -x 580 -y 270 -width 150 -height 145 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab55 \
        -in $site_5_0 -x 50 -y 190 -width 150 -height 145 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab56 \
        -in $site_5_0 -x 750 -y 190 -width 150 -height 145 -anchor nw \
        -bordermode ignore 
    place $site_4_1.lab48 \
        -in $site_4_1 -x 20 -y 10 -width 960 -relwidth 0 -height 485 \
        -relheight 0 -anchor nw -bordermode ignore 
    button $top.but40 \
        -activebackground {#d9d9d9} -background {#d9d9d9} \
        -command destroy_window -foreground {#000000} -highlightcolor black \
        -text Back 
    vTcl:DefineAlias "$top.but40" "back" vTcl:WidgetProc "Treadmill" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tNo40 \
        -in $top -x 20 -y 60 -width 1002 -relwidth 0 -height 532 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but40 \
        -in $top -x 20 -y 10 -width 62 -relwidth 0 -height 35 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .bor22 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

