#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.17
# In conjunction with Tcl version 8.6
#    Oct 15, 2018 04:16:00 PM WIB  platform: Linux

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import recap_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Treadmill (root)
    recap_support.init(root, top)
    root.mainloop()

w = None
def create_Treadmill(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Treadmill (w)
    recap_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Treadmill():
    global w
    w.destroy()
    w = None


class Treadmill:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("1024x600+0+0")
        top.attributes("-fullscreen", True)
        top.title("Treadmill")
        top.configure(highlightcolor="black")



        self.style.configure('TNotebook.Tab', background=_bgcolor)
        self.style.configure('TNotebook.Tab', foreground=_fgcolor)
        self.style.map('TNotebook.Tab', background=
            [('selected', _compcolor), ('active',_ana2color)])
        self.TNotebook1 = ttk.Notebook(top)
        self.TNotebook1.place(relx=0.019, rely=0.1, relheight=0.887
                , relwidth=0.967)
        self.TNotebook1.configure(width=1002)
        self.TNotebook1.configure(takefocus="")
        self.TNotebook1_t0 = Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t0, padding=3)
        self.TNotebook1.tab(0, text="Graph",compound="left",underline="-1",)
        self.TNotebook1_t1 = Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t1, padding=3)
        self.TNotebook1.tab(1, text="Recap",compound="left",underline="-1",)

        self.Canvas1 = Canvas(self.TNotebook1_t0)
        self.Canvas1.place(relx=0.08, rely=0.118, relheight=0.865
                , relwidth=0.821)
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(relief=RIDGE)
        self.Canvas1.configure(selectbackground="#c4c4c4")
        self.Canvas1.configure(width=821)

        self.Label1 = Label(self.TNotebook1_t0)
        self.Label1.place(relx=0.08, rely=0.059, height=17, width=84)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(text='''Heart Rate''')

        self.Label2 = Label(self.TNotebook1_t0)
        self.Label2.place(relx=0.21, rely=0.059, height=17, width=34)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(text='''Max :''')

        self.Label3 = Label(self.TNotebook1_t0)
        self.Label3.place(relx=0.27, rely=0.059, height=17, width=78)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(text='''max_value''')

        self.Label4 = Label(self.TNotebook1_t0)
        self.Label4.place(relx=0.4, rely=0.059, height=17, width=58)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(text='''Average :''')

        self.Label3 = Label(self.TNotebook1_t0)
        self.Label3.place(relx=0.48, rely=0.059, height=17, width=108)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(text='''average_value''')

        self.Labelframe1 = LabelFrame(self.TNotebook1_t1)
        self.Labelframe1.place(relx=0.02, rely=0.02, relheight=0.951
                , relwidth=0.96)
        self.Labelframe1.configure(relief=GROOVE)
        self.Labelframe1.configure(text='''Labelframe''')
        self.Labelframe1.configure(width=960)

        self.Labelframe2 = LabelFrame(self.Labelframe1)
        self.Labelframe2.place(relx=0.229, rely=0.247, relheight=0.299
                , relwidth=0.156, bordermode='ignore')
        self.Labelframe2.configure(relief=GROOVE)
        self.Labelframe2.configure(text='''Average Heart Rate''')
        self.Labelframe2.configure(width=150)

        self.Label5 = Label(self.Labelframe2)
        self.Label5.place(relx=0.133, rely=0.207, height=37, width=114
                , bordermode='ignore')
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(text='''Label''')

        self.Label5 = Label(self.Labelframe2)
        self.Label5.place(relx=0.133, rely=0.552, height=37, width=114
                , bordermode='ignore')
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(text='''BPM''')

        self.Labelframe2 = LabelFrame(self.Labelframe1)
        self.Labelframe2.place(relx=0.417, rely=0.247, relheight=0.299
                , relwidth=0.156, bordermode='ignore')
        self.Labelframe2.configure(relief=GROOVE)
        self.Labelframe2.configure(text='''Total Steps''')
        self.Labelframe2.configure(width=150)

        self.Label5 = Label(self.Labelframe2)
        self.Label5.place(relx=0.133, rely=0.207, height=37, width=114
                , bordermode='ignore')
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(text='''Label''')

        self.Label5 = Label(self.Labelframe2)
        self.Label5.place(relx=0.133, rely=0.552, height=37, width=114
                , bordermode='ignore')
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(text='''Steps''')

        self.Labelframe2 = LabelFrame(self.Labelframe1)
        self.Labelframe2.place(relx=0.604, rely=0.247, relheight=0.299
                , relwidth=0.156, bordermode='ignore')
        self.Labelframe2.configure(relief=GROOVE)
        self.Labelframe2.configure(text='''Burned Calories''')
        self.Labelframe2.configure(width=150)

        self.Label5 = Label(self.Labelframe2)
        self.Label5.place(relx=0.133, rely=0.207, height=37, width=114
                , bordermode='ignore')
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(text='''Label''')

        self.Label5 = Label(self.Labelframe2)
        self.Label5.place(relx=0.133, rely=0.552, height=37, width=114
                , bordermode='ignore')
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(text='''Cal''')

        self.Labelframe2 = LabelFrame(self.Labelframe1)
        self.Labelframe2.place(relx=0.229, rely=0.557, relheight=0.299
                , relwidth=0.156, bordermode='ignore')
        self.Labelframe2.configure(relief=GROOVE)
        self.Labelframe2.configure(text='''Maximum Heart Rate''')
        self.Labelframe2.configure(width=150)

        self.Label5 = Label(self.Labelframe2)
        self.Label5.place(relx=0.133, rely=0.207, height=37, width=114
                , bordermode='ignore')
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(text='''Label''')

        self.Label5 = Label(self.Labelframe2)
        self.Label5.place(relx=0.133, rely=0.552, height=37, width=114
                , bordermode='ignore')
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(text='''BPM''')

        self.Labelframe2 = LabelFrame(self.Labelframe1)
        self.Labelframe2.place(relx=0.417, rely=0.557, relheight=0.299
                , relwidth=0.156, bordermode='ignore')
        self.Labelframe2.configure(relief=GROOVE)
        self.Labelframe2.configure(text='''Step Frequency''')
        self.Labelframe2.configure(width=150)

        self.Label5 = Label(self.Labelframe2)
        self.Label5.place(relx=0.133, rely=0.207, height=37, width=114
                , bordermode='ignore')
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(text='''Label''')

        self.Label5 = Label(self.Labelframe2)
        self.Label5.place(relx=0.133, rely=0.552, height=37, width=114
                , bordermode='ignore')
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(text='''Steps''')

        self.Labelframe2 = LabelFrame(self.Labelframe1)
        self.Labelframe2.place(relx=0.604, rely=0.557, relheight=0.299
                , relwidth=0.156, bordermode='ignore')
        self.Labelframe2.configure(relief=GROOVE)
        self.Labelframe2.configure(text='''Covered''')
        self.Labelframe2.configure(width=150)

        self.Label5 = Label(self.Labelframe2)
        self.Label5.place(relx=0.133, rely=0.207, height=37, width=114
                , bordermode='ignore')
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(text='''Label''')

        self.Label5 = Label(self.Labelframe2)
        self.Label5.place(relx=0.133, rely=0.552, height=37, width=114
                , bordermode='ignore')
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(text='''Km''')

        self.Labelframe2 = LabelFrame(self.Labelframe1)
        self.Labelframe2.place(relx=0.052, rely=0.392, relheight=0.299
                , relwidth=0.156, bordermode='ignore')
        self.Labelframe2.configure(relief=GROOVE)
        self.Labelframe2.configure(text='''Speed''')
        self.Labelframe2.configure(width=150)

        self.Label5 = Label(self.Labelframe2)
        self.Label5.place(relx=0.133, rely=0.207, height=37, width=114
                , bordermode='ignore')
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(text='''Label''')

        self.Label5 = Label(self.Labelframe2)
        self.Label5.place(relx=0.133, rely=0.552, height=37, width=114
                , bordermode='ignore')
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(text='''Km/hr''')

        self.Labelframe2 = LabelFrame(self.Labelframe1)
        self.Labelframe2.place(relx=0.781, rely=0.392, relheight=0.299
                , relwidth=0.156, bordermode='ignore')
        self.Labelframe2.configure(relief=GROOVE)
        self.Labelframe2.configure(text='''Time''')
        self.Labelframe2.configure(width=150)

        self.Label5 = Label(self.Labelframe2)
        self.Label5.place(relx=0.067, rely=0.345, height=37, width=114
                , bordermode='ignore')
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(text='''Label''')

        self.back = Button(top)
        self.back.place(relx=0.019, rely=0.017, height=35, width=62)
        self.back.configure(activebackground="#d9d9d9")
        self.back.configure(command=recap_support.destroy_window)
        self.back.configure(text='''Back''')
        self.back.configure(width=62)






if __name__ == '__main__':
    vp_start_gui()



