#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.17
# In conjunction with Tcl version 8.6
#    Nov 05, 2018 06:16:19 AM WIB  platform: Linux

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import register_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Register (root)
    register_support.init(root, top)
    root.mainloop()

w = None
def create_Register(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Register (w)
    register_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Register():
    global w
    w.destroy()
    w = None


class Register:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 

        top.geometry("1024x600+0+0")
        top.title("Register")
        top.attributes("-fullscreen", True)
        top.configure(highlightcolor="black")



        self.Labelframe1 = LabelFrame(top)
        self.Labelframe1.place(relx=0.02, rely=0.037, relheight=0.271
                , relwidth=0.971)
        self.Labelframe1.configure(relief=GROOVE)
        self.Labelframe1.configure(labelanchor="n")
        self.Labelframe1.configure(text='''Gender''')
        self.Labelframe1.configure(width=980)

        self.left_btn_gender = Button(self.Labelframe1)
        self.left_btn_gender.place(relx=0.01, rely=0.138, height=110, width=62
                , bordermode='ignore')
        self.left_btn_gender.configure(activebackground="#d9d9d9")
        self.left_btn_gender.configure(command=register_support.left_btn_gender)
        self.left_btn_gender.configure(text="◀")

        self.right_btn_gender = Button(self.Labelframe1)
        self.right_btn_gender.place(relx=0.918, rely=0.138, height=110, width=62
                , bordermode='ignore')
        self.right_btn_gender.configure(activebackground="#d9d9d9")
        self.right_btn_gender.configure(command=register_support.right_btn_gender)
        self.right_btn_gender.configure(text="▶")

        self.gender_val = Label(self.Labelframe1)
        self.gender_val.place(relx=0.092, rely=0.138, height=107, width=794
                , bordermode='ignore')
        self.gender_val.configure(activebackground="#d9d9d9")
        self.gender_val.configure(background="#ffffff")
        self.gender_val.configure(text='''Male''',font=("Helvetica", 50))

        self.Labelframe2 = LabelFrame(top)
        self.Labelframe2.place(relx=0.02, rely=0.336, relheight=0.476
                , relwidth=0.466)
        self.Labelframe2.configure(relief=GROOVE)
        self.Labelframe2.configure(labelanchor="n")
        self.Labelframe2.configure(text='''Age''')
        self.Labelframe2.configure(width=470)

        self.age_pul_up_btn = Button(self.Labelframe2)
        self.age_pul_up_btn.place(relx=0.043, rely=0.078, height=35, width=192
                , bordermode='ignore')
        self.age_pul_up_btn.configure(activebackground="#d9d9d9")
        self.age_pul_up_btn.configure(command=register_support.age_pul_up_btn)
        self.age_pul_up_btn.configure(text="▲")

        self.age_sat_up_btn = Button(self.Labelframe2)
        self.age_sat_up_btn.place(relx=0.532, rely=0.078, height=35, width=192
                , bordermode='ignore')
        self.age_sat_up_btn.configure(activebackground="#d9d9d9")
        self.age_sat_up_btn.configure(command=register_support.age_sat_up_btn)
        self.age_sat_up_btn.configure(text="▲")

        self.age_pul_bot_btn = Button(self.Labelframe2)
        self.age_pul_bot_btn.place(relx=0.043, rely=0.784, height=35, width=192
                , bordermode='ignore')
        self.age_pul_bot_btn.configure(activebackground="#d9d9d9")
        self.age_pul_bot_btn.configure(command=register_support.age_pul_bot_btn)
        self.age_pul_bot_btn.configure(text="▼")

        self.age_sat_bot_btn = Button(self.Labelframe2)
        self.age_sat_bot_btn.place(relx=0.532, rely=0.784, height=35, width=192
                , bordermode='ignore')
        self.age_sat_bot_btn.configure(activebackground="#d9d9d9")
        self.age_sat_bot_btn.configure(command=register_support.age_sat_bot_btn)
        self.age_sat_bot_btn.configure(text="▼")

        self.age_puluh = Label(self.Labelframe2)
        self.age_puluh.place(relx=0.043, rely=0.235, height=130, width=190
                , bordermode='ignore')
        self.age_puluh.configure(activebackground="#f9f9f9")
        self.age_puluh.configure(background="#ffffff")
        self.age_puluh.configure(text='''0''',font=("Helvetica", 50))

        self.age_satu = Label(self.Labelframe2)
        self.age_satu.place(relx=0.532, rely=0.235, height=130, width=190
                , bordermode='ignore')
        self.age_satu.configure(activebackground="#f9f9f9")
        self.age_satu.configure(background="#ffffff")
        self.age_satu.configure(text='''0''',font=("Helvetica", 50))

        self.Labelframe2_2 = LabelFrame(top)
        self.Labelframe2_2.place(relx=0.515, rely=0.336, relheight=0.476
                , relwidth=0.476)
        self.Labelframe2_2.configure(relief=GROOVE)
        self.Labelframe2_2.configure(labelanchor="n")
        self.Labelframe2_2.configure(text='''Weight''')
        self.Labelframe2_2.configure(width=480)

        self.wei_pul_up_btn = Button(self.Labelframe2_2)
        self.wei_pul_up_btn.place(relx=0.042, rely=0.078, height=35, width=192
                , bordermode='ignore')
        self.wei_pul_up_btn.configure(activebackground="#d9d9d9")
        self.wei_pul_up_btn.configure(command=register_support.wei_pul_up_btn)
        self.wei_pul_up_btn.configure(text="▲")

        self.wei_pul_bot_btn = Button(self.Labelframe2_2)
        self.wei_pul_bot_btn.place(relx=0.042, rely=0.784, height=35, width=192
                , bordermode='ignore')
        self.wei_pul_bot_btn.configure(activebackground="#d9d9d9")
        self.wei_pul_bot_btn.configure(command=register_support.wei_pul_bot_btn)
        self.wei_pul_bot_btn.configure(text="▼")

        self.wei_sat_up_btn = Button(self.Labelframe2_2)
        self.wei_sat_up_btn.place(relx=0.542, rely=0.078, height=35, width=192
                , bordermode='ignore')
        self.wei_sat_up_btn.configure(activebackground="#d9d9d9")
        self.wei_sat_up_btn.configure(command=register_support.wei_sat_up_btn)
        self.wei_sat_up_btn.configure(text="▲")

        self.wei_sat_bot_btn = Button(self.Labelframe2_2)
        self.wei_sat_bot_btn.place(relx=0.542, rely=0.784, height=35, width=192
                , bordermode='ignore')
        self.wei_sat_bot_btn.configure(activebackground="#d9d9d9")
        self.wei_sat_bot_btn.configure(command=register_support.wei_sat_bot_btn)
        self.wei_sat_bot_btn.configure(text="▼")

        self.wei_puluh = Label(self.Labelframe2_2)
        self.wei_puluh.place(relx=0.042, rely=0.235, height=130, width=190
                , bordermode='ignore')
        self.wei_puluh.configure(activebackground="#f9f9f9")
        self.wei_puluh.configure(background="#ffffff")
        self.wei_puluh.configure(text='''0''',font=("Helvetica", 50))

        self.wei_satu = Label(self.Labelframe2_2)
        self.wei_satu.place(relx=0.542, rely=0.235, height=130, width=190
                , bordermode='ignore')
        self.wei_satu.configure(activebackground="#f9f9f9")
        self.wei_satu.configure(background="#ffffff")
        self.wei_satu.configure(text='''0''',font=("Helvetica", 50))

        self.submit = Button(top)
        self.submit.place(relx=0.238, rely=0.84, height=65, width=532)
        self.submit.configure(activebackground="#d9d9d9")
        self.submit.configure(command=register_support.submit)
        self.submit.configure(text='''Submit''')






if __name__ == '__main__':
    vp_start_gui()



