#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.17
# In conjunction with Tcl version 8.6
#    Nov 05, 2018 05:37:39 AM WIB  platform: Linux
#    Nov 05, 2018 06:11:06 AM WIB  platform: Linux

import sys
import os

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True


gender = ["Male","Female"]
puluh = [0,10,20,30,40,50,60,70,80,90]
satu = [0,1,2,3,4,5,6,7,8,9]
sel_gen = 0
sel_age_pul = 0
sel_age_sat = 0
age = 0
sel_wei_pul = 0
sel_wei_sat = 0
weight = 0


def age_pul_bot_btn():
    print('register_support.age_pul_bot_btn')
    sys.stdout.flush()
    global sel_age_pul
    if sel_age_pul > 0:
        sel_age_pul = sel_age_pul - 1
        w.age_puluh.configure(text=sel_age_pul)  

def age_pul_up_btn():
    print('register_support.age_pul_up_btn')
    sys.stdout.flush()
    global sel_age_pul
    if sel_age_pul < 9:
        sel_age_pul = sel_age_pul + 1
        w.age_puluh.configure(text=sel_age_pul)    

def age_sat_bot_btn():
    print('register_support.age_sat_bot_btn')
    sys.stdout.flush()
    global sel_age_sat
    if sel_age_sat > 0:
        sel_age_sat = sel_age_sat - 1
        w.age_satu.configure(text=sel_age_sat)

def age_sat_up_btn():
    print('register_support.age_sat_up_btn')
    sys.stdout.flush()
    global sel_age_sat
    if sel_age_sat < 9:
        sel_age_sat = sel_age_sat + 1
        w.age_satu.configure(text=sel_age_sat)

def left_btn_gender():
    print('register_support.left_btn_gender')
    sys.stdout.flush()
    global sel_gen
    global gender
    if sel_gen > 0:
        sel_gen = sel_gen - 1
        w.gender_val.configure(text=gender[sel_gen])

def right_btn_gender():
    print('register_support.right_btn_gender')
    sys.stdout.flush()
    global sel_gen
    global gender
    if sel_gen < 1:
        sel_gen = sel_gen + 1
        w.gender_val.configure(text=gender[sel_gen])
    
def submit():
    print('register_support.submit')
    sys.stdout.flush()
    destroy_window()
    global gender
    global puluh
    global satu
    global sel_gen
    global sel_age_pul
    global sel_age_sat
    global age
    global sel_wei_pul
    global sel_wei_sat
    global weight
    
    age = puluh [sel_age_pul] + satu [sel_age_sat]
    weight = puluh [sel_wei_pul] + satu [sel_wei_sat]
    
    fp = open('reg.txt', 'w', os.O_NONBLOCK)
    data = "%d,%d,%s" % (age, weight, gender[sel_gen])
    fp.write(data)
    fp.close()
    print (age, weight, gender[sel_gen])
    

def wei_pul_bot_btn():
    print('register_support.wei_pul_bot_btn')
    sys.stdout.flush()
    global sel_wei_pul
    if sel_wei_pul > 0:
        sel_wei_pul = sel_wei_pul - 1
        w.wei_puluh.configure(text=sel_wei_pul)
    

def wei_pul_up_btn():
    print('register_support.wei_pul_up_btn')
    sys.stdout.flush()
    global sel_wei_pul
    if sel_wei_pul < 9:
        sel_wei_pul = sel_wei_pul + 1
        w.wei_puluh.configure(text=sel_wei_pul)

def wei_sat_bot_btn():
    print('register_support.wei_sat_bot_btn')
    sys.stdout.flush()
    global sel_wei_sat
    if sel_wei_sat > 0:
        sel_wei_sat = sel_wei_sat - 1
        w.wei_satu.configure(text=sel_wei_sat)

def wei_sat_up_btn():
    print('register_support.wei_sat_up_btn')
    sys.stdout.flush()
    global sel_wei_sat
    if sel_wei_sat < 9:
        sel_wei_sat = sel_wei_sat + 1
        w.wei_satu.configure(text=sel_wei_sat)


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import register
    register.vp_start_gui()





